@jakmro/classification ios
software-mansion/react-native-executorch pull request #54
Opened 2024-12-16 09:02 UTC by jakmro

## Description

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improves or adds clarity to existing documentation)

### Tested on
- [x] iOS
- [ ] Android

### Checklist
- [ ] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the documentation accordingly
- [x] My changes generate no new warnings

2024-12-16 12:11 UTC, jakmro commented on examples/computer-vision/assets/classification/android/efficientnet_v2_s_xnnpack.pte
This model will be hosted on Hugging Face

2024-12-16 12:12 UTC, jakmro commented on examples/computer-vision/assets/classification/ios/efficientnet_v2_s_coreml_all.pte
This model will also be hosted on Hugging Face

2024-12-16 21:26 UTC, mkopcins requested changes

2024-12-16 21:26 UTC, mkopcins commented on examples/computer-vision/package.json
>      "metro-config": "^0.81.0",
either revert or write some instructions in readme how to build react-native-executorch-0.1.100.tgz

2024-12-16 21:26 UTC, mkopcins commented on src/models/Classification.ts
> +  const [isModelReady, setIsModelReady] = useState(true);
```suggestion
  const [isModelReady, setIsModelReady] = useState(false);
```

2024-12-16 21:26 UTC, mkopcins commented on src/models/Classification.ts
> +    }
add check for `isModelGenerating`

2024-12-16 21:26 UTC, mkopcins commented on ios/RnExecutorch/models/classification/Constants.h
> +extern const std::string imagenet1k_v1_labels[];
Imo better do constexpr and define it here instead of mm file

2024-12-17 07:57 UTC, mkopcins approved these changes

2024-12-17 07:57 UTC, merged